/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class imghash {
  public static java.math.BigInteger imghash_buffer(String buffer, int bufferSize) {
    return imghashJNI.imghash_buffer(buffer, bufferSize);
  }

  public static java.math.BigInteger imghash_file(String fileName) {
    return imghashJNI.imghash_file(fileName);
  }

  public static String imghash_file_hex(String fileName) {
    return imghashJNI.imghash_file_hex(fileName);
  }

}
