/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.sociohub.imghash;

public class imghashJNI {

    static {
        try {
            NativeLoader loader = new NativeLoader();
            loader.loadLibrary("imghash-java");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Native code library failed to load. \n" + e);
            System.exit(1);
        }
    }

  public final static native java.math.BigInteger imghash_buffer(byte[] jarg1);
  public final static native java.math.BigInteger imghash_file(String jarg1);
  public final static native String imghash_file_hex(String jarg1);
}
